import type { Locale } from "@/lib/shadowbox/prefs";

const en = {
  title: "Shadowbox",
  home: "Home",
  search: "Search",
  searchPlaceholder: "Search the record",
  menu: "Menu",
  noMatch: "No match in the record.",
  timeline: "Timeline",
  admin: "Admin",
  commands: "Commands",
  uniforms: "Uniforms",
  decorations: "Decorations",
  onduty: "On Duty",
  offduty: "Off Duty",
  ops: "Ops",
  map: "Map",
  schools: "Schools",
  necs: "NECs",
  dateNeeded: "Date needed",
  sources: "Sources",
  contact: "Contact",
  guestbook: "Guestbook",
  memories: "Memories",
  settings: "Settings",
  close: "Close",
  made: "Made by Myself & Grok, 2026",
  bio: "Sergio Schickler enlisted in Miami on 30 June 1997 and transferred to the Fleet Reserve on 28 February 2018 as a Chief Electronics Technician. SW is the Enlisted Surface Warfare Specialist pin, earned on USS Frank Cable. EXW is the Enlisted Expeditionary Warfare Specialist pin, earned later. The last duty station was Naval Hospital Jacksonville.",
  pathTitle: "The same years, one line",
  pathLead: "Rank, assignments, and deployments share one axis. A bar opens the explanation.",
  eventsNote: "The last track is public history during these years. It is not part of the service record.",
  footerNav: "More",
  language: "Language",
  english: "English",
  portuguese: "Português",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  system: "System",
  settingsTitle: "Settings",
  settingsLead: "Language changes the menus and buttons. The service record stays in English until the Portuguese record is finished, and official names stay as written.",
  schoolsLead: "Courses in the order they were recorded. Open a row for the explanation, the place, and what the course was for.",
  commandsLead: "The six commands. Each row is the crest, the rating badge on the way in, loose ribbons, and the rating badge on the way out. Slide left for in-theater commands, sponsors, partners, customers, and exercises.",
  necsLead: "Navy Enlisted Classifications in the order awarded. A code that later changed shows the current code. Open a row for the criteria.",
};

const pt: typeof en = {
  title: "Shadowbox",
  home: "Início",
  search: "Buscar",
  searchPlaceholder: "Buscar no registro",
  menu: "Menu",
  noMatch: "Nada encontrado no registro.",
  timeline: "Linha do tempo",
  admin: "Admin",
  commands: "Comandos",
  uniforms: "Uniformes",
  decorations: "Condecorações",
  onduty: "Em serviço",
  offduty: "Fora de serviço",
  ops: "Operações",
  map: "Mapa",
  schools: "Escolas",
  necs: "NECs",
  dateNeeded: "Data em aberto",
  sources: "Fontes",
  contact: "Contato",
  guestbook: "Livro de visitas",
  memories: "Memórias",
  settings: "Ajustes",
  close: "Fechar",
  made: "Feito por Mim & Grok, 2026",
  bio: "Sergio Schickler alistou-se em Miami em 30 de junho de 1997 e passou à reserva da frota em 28 de fevereiro de 2018, como Chief Electronics Technician. SW é o distintivo de Enlisted Surface Warfare Specialist, ganho no USS Frank Cable. EXW é o de Enlisted Expeditionary Warfare Specialist, ganho depois. O último posto foi o Naval Hospital Jacksonville.",
  pathTitle: "Os mesmos anos, numa linha",
  pathLead: "Posto, funções e deslocamentos partilham um eixo. Uma barra abre a explicação.",
  eventsNote: "A última faixa é história pública destes anos. Não faz parte do registro de serviço.",
  footerNav: "Mais",
  language: "Idioma",
  english: "English",
  portuguese: "Português",
  theme: "Tema",
  light: "Claro",
  dark: "Escuro",
  system: "Sistema",
  settingsTitle: "Ajustes",
  settingsLead: "O idioma muda os menus e os botões. O registro de serviço continua em inglês até o registro em português ficar pronto, e os nomes oficiais ficam como foram escritos.",
  schoolsLead: "Cursos na ordem em que foram registrados. Abra uma linha para a explicação, o lugar e para que servia o curso.",
  commandsLead: "Os seis comandos. Cada fileira é o distintivo, o distintivo de posto na entrada, fitas soltas, e o distintivo de posto na saída. Deslize para o comando no teatro, patrocinadores, parceiros, clientes e exercícios.",
  necsLead: "Classificações de praça (NEC) na ordem em que foram concedidas. Código que mudou mostra o código atual. Abra a linha para o critério.",
};

export type Chrome = typeof en;

export function chrome(locale: Locale): Chrome {
  return locale === "pt" ? pt : en;
}
