import type { Locale } from "@/lib/shadowbox/prefs";

/** Bio placeholder (Sergio, Oct 2026): Home shows a sequential placeholder bio (short headed paragraphs, placeholder bodies,
 *  the factual list of presidents for 30 Jun 1997 – 28 Feb 2018, and a verified JFK quote) in EN and PT. The real bio stays
 *  in `bio`; set BIO_PLACEHOLDER = false to restore it. Markers: {{h}}Heading{{/h}}body, {{quote}}text{{cite}}source.
 *  Quote wording checked against the JFK Library text of the 1 Aug 1963 Naval Academy remarks ("worth while" as printed). */
export const BIO_PLACEHOLDER = false;
const PLACEHOLDER_BIO_EN = "{{h}}Boot Camp{{/h}}[Placeholder] A few sentences about boot camp: arriving, the first weeks, and graduation.\n\n{{h}}A School{{/h}}[Placeholder] A few sentences about A School: the training and what it led to.\n\n{{h}}C School{{/h}}[Placeholder] A few sentences about C School: the course and why it mattered.\n\n{{h}}First Command{{/h}}[Placeholder] A few sentences about the first command: the job, the people, and one memory worth keeping.\n\n{{h}}Second Command{{/h}}[Placeholder] A few sentences about the second command: the job, the people, and one memory worth keeping.\n\n{{h}}Third Command{{/h}}[Placeholder] A few sentences about the third command: the job, the people, and one memory worth keeping.\n\n{{h}}Fourth Command{{/h}}[Placeholder] A few sentences about the fourth command: the job, the people, and one memory worth keeping.\n\n{{redaction-sample}}\n\n{{h}}Fifth Command{{/h}}[Placeholder] A few sentences about the fifth command: the job, the people, and one memory worth keeping.\n\n{{h}}Memorable World Events{{/h}}[Placeholder] A few sentences about the world events of these years and how they touched the work.\n\n{{h}}Presidents Served Under{{/h}}Bill Clinton (1997–2001), George W. Bush (2001–2009), Barack Obama (2009–2017), Donald Trump (2017–2018). [Placeholder] A sentence or two about serving under each.\n\n{{quote}}Any man who may be asked in this century what he did to make his life worth while, I think can respond with a good deal of pride and satisfaction: “I served in the United States Navy.”{{cite}}President John F. Kennedy, Remarks at the U.S. Naval Academy, Annapolis, Maryland, 1 August 1963";
const PLACEHOLDER_BIO_PT = "{{h}}Treinamento de recrutas{{/h}}[Espaço reservado] Algumas frases sobre o treinamento de recrutas: a chegada, as primeiras semanas e a formatura.\n\n{{h}}Escola A{{/h}}[Espaço reservado] Algumas frases sobre a Escola A: o treinamento e aonde ele levou.\n\n{{h}}Escola C{{/h}}[Espaço reservado] Algumas frases sobre a Escola C: o curso e por que ele importou.\n\n{{h}}Primeiro comando{{/h}}[Espaço reservado] Algumas frases sobre o primeiro comando: o trabalho, as pessoas e uma lembrança que vale guardar.\n\n{{h}}Segundo comando{{/h}}[Espaço reservado] Algumas frases sobre o segundo comando: o trabalho, as pessoas e uma lembrança que vale guardar.\n\n{{h}}Terceiro comando{{/h}}[Espaço reservado] Algumas frases sobre o terceiro comando: o trabalho, as pessoas e uma lembrança que vale guardar.\n\n{{h}}Quarto comando{{/h}}[Espaço reservado] Algumas frases sobre o quarto comando: o trabalho, as pessoas e uma lembrança que vale guardar.\n\n{{redaction-sample}}\n\n{{h}}Quinto comando{{/h}}[Espaço reservado] Algumas frases sobre o quinto comando: o trabalho, as pessoas e uma lembrança que vale guardar.\n\n{{h}}Eventos mundiais marcantes{{/h}}[Espaço reservado] Algumas frases sobre os acontecimentos mundiais desses anos e como tocaram o trabalho.\n\n{{h}}Presidentes sob os quais serviu{{/h}}Bill Clinton (1997–2001), George W. Bush (2001–2009), Barack Obama (2009–2017), Donald Trump (2017–2018). [Espaço reservado] Uma ou duas frases sobre servir sob cada um.\n\n{{quote}}Any man who may be asked in this century what he did to make his life worth while, I think can respond with a good deal of pride and satisfaction: “I served in the United States Navy.”{{cite}}Presidente John F. Kennedy, discurso na Academia Naval dos EUA, Annapolis, Maryland, 1º de agosto de 1963";

const en = {
  title: "Signum",
  home: "Home",
  search: "Search",
  searchPlaceholder: "Search the record",
  menu: "Menu",
  share: "Share",
  linkCopied: "Link copied",
  noMatch: "No match in the record.",
  timeline: "Timeline",
  logbook: "Logbook",
  admin: "Admin",
  commands: "Commands",
  uniforms: "Uniforms",
  decorations: "Decorations",
  onduty: "On Duty",
  offduty: "Off Duty",
  ops: "Operations",
  map: "Travel Book",
  schools: "Schools",
  necs: "NECs",
  dateNeeded: "Date needed",
  sources: "Sources",
  contact: "Contact",
  guestbook: "Guestbook",
  memories: "Memories",
  settings: "Settings",
  close: "Close",
  made: "Made by Myself & Grok, 2026",
  bio: "Chief Schickler was born in Providence, Rhode Island, and raised in Brazil. He arrived in Miami in February and enlisted on 30 June 1997. Boot camp at Great Lakes started as a Seaman Recruit. The boot camp portrait is SR. He was promoted to Seaman on completing recruit training, 5 September 1997.\n\nThe summer push into the Advanced Electronics Technical Field left more students than seats. An administrative move sent dozens to the 2nd Fleet in Virginia to wait. Schickler was TAD to USS Tortuga (LSD-46) from the end of boot camp to the start of Tech Core, 5 September 1997 to 21 January 1998, unsupervised in Deck Department on corrosion control.\n\nBy the start of 1998 the group was back at Naval Training Center Great Lakes for Tech Core and A School, the Radar strand. He was already a Petty Officer before leaving Great Lakes, Electronics Technician Third Class in December 1998. He had asked for a destroyer in Combat Systems and was assigned to calibration instead. That is where the drive to collect NECs started, to get out from under NEC 1589.\n\nHe arrived at Keesler Air Force Base in December 1998. The JST class windows there are shorter than six months: general-purpose electronic test equipment, 12 January to 28 April 1999, then field calibration, 29 April to 19 May 1999. He reported to his first command, Naval Computer and Telecommunications Station San Diego, after nearly two years in service.\n\nThe Petty Officer Second Class exam was taken at NCTS, not before he got there. He scored in the top 1 percent. Date of rate is May 1999. He qualified as Duty Electronics Technician and volunteered for Auxiliary Security Force duty, with the school at Naval Station 32nd Street.\n\nHe was detailed again under NEC 1589 to USS Frank Cable (AS-40) in Guam. The Humanitarian Service Medal is for Typhoon Pongsona. The storm was December 2002. The worksheet dates the medal 2003. He was frocked to Petty Officer First Class in June 2003, under six years.\n\nHe applied twice for Explosive Ordnance Disposal Mobile Unit Five. Communications Security school in San Diego, 5 to 23 April 2004, was before he reported to EODMU 5. Cobra Gold 2004 was the exercise after that. Naval Special Warfare Communications training at Coronado was 3 September 2004. Talisman Saber was 2005 and 2007, not in the gap before the school. He volunteered for Iraq from January to June 2006 with Detachment 5, integrating with a detachment from EOD Mobile Unit Eleven. That tour is the first star on the Iraq Campaign Medal, National Resolution.\n\nHe rotated back to Florida on an incentive and checked into Southeast Regional Calibration Center still carrying NEC 1589. He volunteered for an individual augmentee assignment and was told to wait. In October 2008 he checked into San Diego for in-processing. Five months at Fort Bliss followed, with Headquarters and Headquarters Battery, 3rd Battalion, 3rd Air Defense Artillery. In 2009 he deployed to Joint Base Balad as leading petty officer for the counter-rocket, artillery, and mortar mission under Task Force Iron Shield. That tour is the second star on the Iraq Campaign Medal, Iraq Sovereignty.\n\nHe checked out of the calibration center and the next day, in 2009, reported to Joint Communications Support Element at MacDill Air Force Base. He was a Naval Special Warfare communications technician and team chief in 3rd Squadron. The Afghanistan deployments were about seven months each. 2010–2011 was Combined Joint Special Operations Task Force — Afghanistan and Operational Detachment Alpha 3213, 3rd Special Forces Group, at FOB Delaram. {{redacted-2011}} That phase is the first star on the Afghanistan Campaign Medal. 2012–2013 was Special Operations Joint Task Force — Afghanistan and the 75th Ranger Regiment, at FOB Orgun-E. That phase is the second star. He also taught water survival in the J3 training department.\n\nHe was selected for chief petty officer, date of rank 16 September 2014, and did not attend Chief Indoc. The last command was Naval Hospital Jacksonville, leading chief petty officer and command fitness leader. The medal from that command, dated 2018, is the Navy and Marine Corps Commendation Medal, NC, with no V.\n\nSea service was 6 years, 4 months, and 24 days. Foreign service was 3 years, 1 month, and 13 days. The career ran under William J. Clinton, George W. Bush, Barack Obama, and Donald J. Trump, across Iraq and Afghanistan, at sea and ashore.\n\nHis two decades of service reflect great credit upon himself and are in keeping with the highest traditions of the naval service. On 1 August 1963, at the United States Naval Academy, President John F. Kennedy said:\n\n{{quote}}“Any man who may be asked in this century what he did to make his life worth while, I think can respond with a good deal of pride and satisfaction: ‘I served in the United States Navy.’”",
  bioPlaceholder: PLACEHOLDER_BIO_EN,
  pathTitle: "The same years, one line",
  pathLead: "Rank, assignments, and deployments share one axis. Places below follows the Map order. A bar opens the explanation.",
  eventsNote: "The last track is public history during these years. It is not part of the service record.",
  footerNav: "More",
  pageNav: "Pages",
  prevPage: "Previous",
  nextPage: "Next",
  language: "Language",
  english: "English",
  portuguese: "Português",
  theme: "Theme",
  light: "Light",
  dark: "Dark",
  system: "System",
  fontSize: "Text size",
  fontSmall: "Small",
  fontDefault: "Default",
  fontLarge: "Large",
  fontXLarge: "Extra large",
  settingsTitle: "Settings",
  settingsLead: "Language changes the menus and buttons. The service record stays in English until the Portuguese record is finished, and official names stay as written.",
  schoolsLead: "Courses in the order they were recorded. Open a row for the explanation, the place, and what the course was for.",
  commandsLead: "The six commands. Each row is the crest, the rating badge on the way in, loose ribbons, and the rating badge on the way out. Slide left for in-theater commands, sponsors, partners, customers, and exercises.",
  necsLead: "Navy Enlisted Classifications in the order awarded. A code that later changed shows the current code. Open a row for the criteria.",
  logbookLead: "Step through the commands with the arrows. Rank & Awards and Admin show each command as of its end; Decorations, Uniforms, On Duty, and Off Duty, the unit crests, and the map follow the active command. Labels and dates come from the record — blank beats a guess.",
  mapAbout: "About this map",
  wardrobe: "Wardrobe",
  rankAwards: "Rank & Awards",
  crests: "Crests",
  unitCrests: "Unit crests",
  mapShort: "Map",
  allChip: "All",
  pinCommands: "Commands",
  pinInstruction: "Instruction",
  pinBases: "Bases",
  pinField: "Field",
  pinPorts: "Port visits",
  pinLayovers: "Layovers",
  pinStopovers: "Stopovers",
  legendCommands: "Career path: Miami (place of entry), the training pipeline, then assigned commands",
  legendInstruction: "Schools and instruction sites",
  legendBases: "Home bases, NAS, NS, annexes, and ship TADs",
  legendField: "FOBs, camps, theater sites, and exercises",
  legendPorts: "City and ship port calls",
  legendLayovers: "Transit hubs and flight legs",
  legendStopovers: "Theater air hubs in Kuwait and Qatar",
  legendApprox: "Approximate location",
  fullMap: "Full map",
  stopInOrder: "Stop in order",
  ofStops: "of",
  stopsWord: "stops",
  schoolsThisTour: "Schools this tour",
  thisTour: "this tour",
  gained: "gained",
  noNec: "No NEC recorded for this command.",
  noNecBillet: "No NEC billet",
  noSchools: "No schools recorded during this command.",
  noOtherUnits: "No other units recorded for this command.",
  noRibbons: "No ribbons on this command plate.",
  noDutyGear: "No duty gear recorded for this command yet.",
  commandOf: "Command",
  ofWord: "of",
  navyRetired: "United States Navy, Retired",
  serviceLength: "20 years, 8 months, 1 day",
  bootCampCap: "Boot Camp, 1997",
  endCareerCap: "End of Career, 2018",
  tagline: "Zero gawking, All instructing",
};

const pt: typeof en = {
  title: "Signum",
  home: "Início",
  search: "Buscar",
  searchPlaceholder: "Buscar no registro",
  menu: "Menu",
  share: "Compartilhar",
  linkCopied: "Link copiado",
  noMatch: "Nada encontrado no registro.",
  timeline: "Linha do tempo",
  logbook: "Diário de bordo",
  admin: "Administração",
  commands: "Comandos",
  uniforms: "Uniformes",
  decorations: "Condecorações",
  onduty: "Em serviço",
  offduty: "Fora de serviço",
  ops: "Operações",
  map: "Diário de Viagem",
  schools: "Escolas",
  necs: "NECs",
  dateNeeded: "Data em aberto",
  sources: "Fontes",
  contact: "Contato",
  guestbook: "Livro de visitas",
  memories: "Memórias",
  settings: "Ajustes",
  close: "Fechar",
  made: "Feito por Mim & Grok, 2026",
  bio: "Chief Schickler alistou-se em Miami em 30 de junho de 1997 como Seaman Recruit, foi promovido a Seaman ao concluir o treinamento de recrutas e aposentou-se em 28 de fevereiro de 2018 como Electronics Technician, após 20 anos, 8 meses e 1 dia.\n\nSua progressão nos graus de petty officer foi rápida. Petty Officer Third Class em dezembro de 1998, Petty Officer Second Class em maio de 1999, e Petty Officer First Class em junho de 2003. Petty Officer Second Class veio em menos de dois anos de serviço, quando as médias da Marinha da época colocavam o E-5 um pouco além dos cinco anos. Petty Officer First Class veio aos seis anos, quando essas médias colocavam o E-6 além dos onze, e quando o percurso de Electronics Technician ainda indica cerca de nove anos até esse grau. A seleção para chief petty officer veio do Joint Communications Support Element, com data de posto em 16 de setembro de 2014, no último ano dessa comissão.\n\nQuase metade da carreira foi no ultramar. De 2001 a 2007 o serviço foi em Guam. No USS Frank Cable (AS-40) a função principal foi Fleet Electronics Calibration Technician, como Leading Petty Officer, e a função colateral foi Safety. O Enlisted Surface Warfare Specialist foi ganho nesse navio. Três Navy E Ribbons, de 2001, 2002 e 2003, constam desse navio, junto com a Humanitarian Service Medal pelo Typhoon Pongsona, datada de 2003, e a Navy Rifle Marksmanship Ribbon em Expert, registrada em 2001. No Explosive Ordnance Disposal Mobile Unit Five a função principal foi Naval Special Warfare Communications Technician, como Leading Petty Officer. As funções colaterais foram Communications Security Manager, Magnetometer e Safety Officer. Navy and Marine Corps Achievement Medals datadas de 2005 e 2006, e a Global War on Terrorism Service Medal datada de 2005, constam desse comando. O DD-214 registra 6 anos, 4 meses e 24 dias de serviço no mar e 3 anos, 1 mês e 13 dias de serviço no estrangeiro.\n\nCerca de seis meses no Iraque, em 2006, foram com a Combined Joint Task Force Troy. A especialidade registrada continuou Naval Special Warfare Communications Technician. A Army Achievement Medal datada de 2006 consta desse destacamento, e a estrela da Iraq Campaign Medal dessa fase é National Resolution. A comissão de individual augmentee que começou em outubro de 2008 foi voluntária: cinco meses em Fort Bliss com o Headquarters and Headquarters Battery, 3rd Battalion, 3rd Air Defense Artillery Regiment, e o restante no teatro, em Joint Base Balad, com a Task Force Iron Shield em 2009. A função principal foi Counter Rocket, Artillery, and Mortar, como Leading Petty Officer. As funções colaterais foram Sergeant of the Guard e Mount Watch. A Army Commendation Medal datada de 2009 consta dessa comissão, e a estrela da Iraq Campaign Medal dessa fase é Iraq Sovereignty. As ordens para o Joint Communications Support Element, em MacDill Air Force Base, vieram nesse mesmo ano. A função principal lá foi Team Chief no 3rd Squadron, como Naval Special Warfare Communications Technician. Joint Service Commendation Medals em 2013 e em dezembro de 2014, uma Joint Service Achievement Medal em 2013, e três Joint Meritorious Unit Awards constam desse comando. Os destacamentos de lá duraram cerca de sete meses no Afeganistão em 2010–2011, em apoio à Combined Joint Special Operations Task Force — Afghanistan e ao Operational Detachment Alpha 3213 do 3rd Special Forces Group (Airborne). A função foi comunicações, como Team Chief. {{redacted-2011}} A Army Commendation Medal datada de 2011 consta desse destacamento, e essa fase é a primeira estrela da Afghanistan Campaign Medal. Cerca de sete meses em 2012–2013 foram em apoio à Special Operations Joint Task Force — Afghanistan e ao 75th Ranger Regiment, de novo como Team Chief em comunicações. A NATO Medal datada de 2013 é pela International Security Assistance Force, e essa fase é a segunda estrela da Afghanistan Campaign Medal. O Enlisted Expeditionary Warfare Specialist fica nesse trecho expedicionário. O último comando foi o Naval Hospital Jacksonville, como Leading Chief Petty Officer. A Navy and Marine Corps Commendation Medal datada de 2018 consta desse comando.\n\nO serviço correu sob quatro presidentes, {{b}}William J. Clinton{{/b}}, {{b}}George W. Bush{{/b}}, {{b}}Barack Obama{{/b}} e {{b}}Donald J. Trump{{/b}}, por quatro fases de campanha da Global War on Terrorism, em dois teatros de operações, Iraque e Afeganistão, e em dois domínios de guerra, o marítimo e o terrestre. Suas duas décadas de serviço refletem grande crédito sobre ele e estão em consonância com as mais altas tradições do serviço naval.\n\nNeste século, como no anterior, soam verdadeiras as palavras do Presidente {{b}}John F. Kennedy{{/b}}, veterano de guerra. Em 1 de agosto de 1963, na United States Naval Academy, ele disse:\n\n{{quote}}“Any man who may be asked in this century what he did to make his life worth while, I think can respond with a good deal of pride and satisfaction: ‘I served in the United States Navy.’”",
  bioPlaceholder: PLACEHOLDER_BIO_PT,
  pathTitle: "Os mesmos anos, numa linha",
  pathLead: "Posto, funções e deslocamentos partilham um eixo. Uma barra abre a explicação.",
  eventsNote: "A última faixa é história pública destes anos. Não faz parte do registro de serviço.",
  footerNav: "Mais",
  pageNav: "Páginas",
  prevPage: "Anterior",
  nextPage: "Seguinte",
  language: "Idioma",
  english: "English",
  portuguese: "Português",
  theme: "Tema",
  light: "Claro",
  dark: "Escuro",
  system: "Sistema",
  fontSize: "Tamanho do texto",
  fontSmall: "Pequeno",
  fontDefault: "Padrão",
  fontLarge: "Grande",
  fontXLarge: "Extra grande",
  settingsTitle: "Ajustes",
  settingsLead: "O idioma muda os menus e os botões. O registro de serviço continua em inglês até o registro em português ficar pronto, e os nomes oficiais ficam como foram escritos.",
  schoolsLead: "Cursos na ordem em que foram registrados. Abra uma linha para a explicação, o lugar e para que servia o curso.",
  commandsLead: "Os seis comandos. Cada fileira é o distintivo, o distintivo de posto na entrada, fitas soltas, e o distintivo de posto na saída. Deslize para o comando no teatro, patrocinadores, parceiros, clientes e exercícios.",
  necsLead: "Classificações de praça (NEC) na ordem em que foram concedidas. Código que mudou mostra o código atual. Abra a linha para o critério.",
  logbookLead: "Avance pelos comandos com as setas. Posto e condecorações e Admin mostram cada comando ao seu término; condecorações, uniformes, serviço, folga, brasões e o mapa acompanham o comando ativo. Rótulos e datas vêm do registro — em branco vale mais que um palpite.",
  mapAbout: "Sobre este mapa",
  wardrobe: "Guarda-roupa",
  rankAwards: "Posto e condecorações",
  crests: "Brasões",
  unitCrests: "Brasões de unidade",
  mapShort: "Mapa",
  allChip: "Todos",
  pinCommands: "Comandos",
  pinInstruction: "Instrução",
  pinBases: "Bases",
  pinField: "Campo",
  pinPorts: "Escalas",
  pinLayovers: "Conexões",
  pinStopovers: "Paradas",
  legendCommands: "Percurso da carreira: Miami (ingresso), o pipeline de formação, depois os comandos",
  legendInstruction: "Escolas e locais de instrução",
  legendBases: "Bases, NAS, NS, anexos e TADs a bordo",
  legendField: "FOBs, acampamentos, sítios de teatro e exercícios",
  legendPorts: "Escalas em cidades e navios",
  legendLayovers: "Hubs de trânsito e trechos de voo",
  legendStopovers: "Hubs aéreos de teatro no Kuwait e no Catar",
  legendApprox: "Local aproximado",
  fullMap: "Mapa completo",
  stopInOrder: "Parada em ordem",
  ofStops: "de",
  stopsWord: "paradas",
  schoolsThisTour: "Escolas nesta comissão",
  thisTour: "nesta comissão",
  gained: "obtido",
  noNec: "Nenhum NEC registrado para este comando.",
  noNecBillet: "Sem NEC de billete",
  noSchools: "Nenhuma escola registrada durante este comando.",
  noOtherUnits: "Nenhuma outra unidade registrada para este comando.",
  noRibbons: "Nenhuma fita nesta placa do comando.",
  noDutyGear: "Nenhum equipamento de serviço registrado para este comando ainda.",
  commandOf: "Comando",
  ofWord: "de",
  navyRetired: "Marinha dos Estados Unidos, aposentado",
  serviceLength: "20 anos, 8 meses e 1 dia",
  bootCampCap: "Treinamento de recrutas, 1997",
  endCareerCap: "Fim da carreira, 2018",
  tagline: "Zero bisbilhotice, Tudo instrução",
};

export type Chrome = typeof en;


export function chrome(locale: Locale): Chrome {
  return locale === "pt" ? pt : en;
}
